options:
  type:    INNODB
  collate: utf8_unicode_ci
  charset: utf8

Sandbox:
  connection: default
  tableName:  tests
  columns:
    name:
      notblank: true
      type: string(50)
    firstname:
      notblank: true
      type: string(50)